### PR TITLE
New IAF implementation with inverse operation

### PR DESCRIPTION
**Pull request by stefanwebb**
This pull request contains a new IAF implementation that uses a slightly different formula (also from the IAF paper). This matches the TF implementation and should improve performance I believe on the DMM example. The old version of IAF is moved to class `InverseAutoregressiveFlowStable`.

Explicit inverses are calculated for both `InverseAutoregressiveFlow` and `InverseAutoregressiveFlowStable` when required.

I've added in MaskedAutoregressiveFlow and NeuralAutoregressiveFlow. For these, the numerical gradient doesn't seem to match the analytical one, but I don't think it's due to an incorrect formula. I think it's caused by limitations in the method used to calculate the numerical gradient. I think that the gradient calculation for MAF could work if I use dx/dy rather than dy/dx (which has to be calculated by inverting the operation). I'm not sure about NAF...

I've separated out the tests for autoregressive flows from those for autoregressive networks.

### CODE REVIEW

**Comment by martinjankowiak** [comment]
@stefanwebb thanks! can you please split this into at least two PRs? maybe peeling off the NeuralAutoregressive* bits? it's difficult to review 700 lines of code in one go

**Comment by stefanwebb** [comment]
Let me have another go at submitting this PR and the FlipFlow one tomorrow. I'll break this one into three and remove the IAF stuff from the FlipFlow one so they're all independent

**Comment by martinjankowiak** [comment]
great, thanks. maybe while you're at it rename flipflow to something like `PermutedDistribution`? doesn't something like that seem a better fit?

**Comment by stefanwebb** [comment]
Yeah I agree

**Comment by fritzo** [comment]
@stefanwebb what's the status of this PR? No hurry, I just want to make sure you're unblocked.

**Comment by stefanwebb** [comment]
Nothing is blocking me at the moment, except an important conference deadline tomorrow. I look forward to getting back on this on Friday though

**Comment by karalets** [comment]
Hey,

I see you closed this issue. However, I was quite fond of it. Any updates
on how this is going?

Cheers,

T.

**Comment by stefanwebb** [comment]
Ah sorry, yes I'm breaking it up into several pull requests, which I'll do in sequence

**Comment by stefanwebb** [comment]
About to do the first one...

**Comment by stefanwebb** [comment]
P.s. I'm glad you liked it!

**Pull request closed without merging**
