### PR TITLE
typo in bayesian_regression.ipynb

### PR DESCRIPTION
**Pull request by manuelhaussmann**
Missing brackets in print statement

### CODE REVIEW

**Comment by jpchen** [comment]
this notebook is built with python2.7 which is why there are no parens. to make this runnable, there would need to be `from __future__ import print_function` and all the other print statements would need to be changed, otherwise we need to reubuild the notebooks with python3. currently this wont be able to run. would you mind if i closed this and opened an issue for py3 support?

**Comment by manuelhaussmann** [comment]
Sure, go ahead!

However are you sure that the notebook is built with python2.7? The other print statements already follow python3 style and the notebook ran without problems (except for that line) when I worked through the example earlier today.

**Comment by fritzo** [comment]
> to make this runnable, there would need to be `from __future__ import print_function`

`print("foo")` runs fine in Python 2. It means the same as `print ("foo")` which means the same as `print "foo"`.

**Comment by manuelhaussmann** [comment]
@fritzo Thanks for the clarification. It's been a while that I looked at python2.7

**Comment by jpchen** [comment]
ah @fritzo is right havent used that syntax. 

@manuelhaussmann do you want to reopen this PR? this is a change worth making so it will run for people using python 3

**Comment by manuelhaussmann** [comment]
@jpchen I have reopened it.

**Pull request merged**
