### PR TITLE
Remove Pyro distributions migrated to PyTorch

### PR DESCRIPTION
**Pull request by neerajprad**
Addresses #638

This simply removes all the distributions that are already migrated to PyTorch. In subsequent PRs, we will rename the method names to align with `torch.distributions`, and finally change the batch semantics and remove/update most of our existing test suite.

### CODE REVIEW

**Comment by jpchen** [comment]
this only removes the ones that have _already been migrated_ correct? so we shouldnt be losing support for any existing distributions in this PR?

**Comment by neerajprad** [comment]
> this only removes the ones that have already been migrated correct? so we shouldnt be losing support for any existing distributions in this PR?

That's right, not yet. :) What changes with this PR is that you need to build PyTorch master to be able to use Pyro's `dev` branch.

**Comment by neerajprad** [comment]
There is some travis CI slowdown, so it might take a while for the tests to start running.

**Comment by neerajprad** [comment]
Should be good to merge once tests pass.

**Pull request merged**
