### PR TITLE
Fix DMM example with --num-iafs > 0

### LINKED ISSUE #721: DMM Example  Model and guide dims disagree when IAF is applied
When the number of IAF is non zero, the latent dimension changes to the same value as the batch size.

### PR DESCRIPTION
**Pull request by neerajprad**
We needed some shape fixes to TransformedDistribution to fix the DMM example with IAF. There is still the issue with NAN loss - #711 that seems to have been introduced much earlier (I checked until November 2017). 

Fixes #721.

### CODE REVIEW

**Comment by neerajprad** [comment]
@fritzo - Can I just remove the pyro `TransformedDistribution` and `Bijector` classes and use the corresponding PyTorch implementations? I will modify the `InverseAutoregressiveFlow` class to inherit off of torch `Bijector`. I will probably need that for HMC too.

**Comment by neerajprad** [comment]
> I agree the automated example discovery logic is getting kludgey.

Its not that bad yet. :) Just added a TODO to keep in mind that if we are messing around with that part too much, it might be worth revisiting.

**Comment by fritzo** [comment]
> Can I just remove the pyro `TransformedDistribution`

I am working on that in this branch https://github.com/uber/pyro/tree/torch-transformed-and-iaf
Feel free to take over the work if you like. I can open a PR if you want to discuss.

**Comment by neerajprad** [comment]
> I am working on that in this branch https://github.com/uber/pyro/compare/torch-transformed-and-iaf Feel free to take over the work if you like. I can open a PR if you want to discuss.

Yeah, I will need this for HMC. Unfortunately, we can't mix `RandomPrimitive` and other distributions, since `RandomPrimitive` instances can't support properties (we need to pass in distribution parameters to those methods). As such they are not interchangeable with torch distributions.

**Pull request merged**
