### PR TITLE
Switch to using PyTorch distributions by default

### PR DESCRIPTION
**Pull request by fritzo**
This flips the switch to start using PyTorch distributions by default, only if they are available. If they are not available (i.e. if an older PyTorch version is installed), then the old Pyro distributions will be used instead.

Note that a few Pyro distributions are currently being implemented in PyTorch, and are not switched in this PR:
- Binomial: Alican
- Multinomial: Alican
- MultivariateNormal: Brooks
- HalfCauchy: JP
- Poisson: Rachit
- LogNormal: Fritz
- Delta: may not need a PyTorch wrapper at all

### CODE REVIEW

**Comment by martinjankowiak** [comment]
congrats to everyone who put in the hardwork to make this happen!

**Comment by neerajprad** [comment]
There was some AWS_KEY in the env that was messing up the S3 download. I removed that restarted the tests.

**Comment by fritzo** [comment]
@null-a Would you mind taking a look at the [error in air](https://travis-ci.org/uber/pyro/jobs/327992413#L771)? It looks like `batch_size` semantics may have changed, but I have been unable to pinpoint where the tensor of incorrect size `torch.Size((50,))` is created.

This is the last remaining bug blocking us from switching to PyTorch distributions. I spent an hour or so last night trying to diagnose it, and I'd appreciate any help you could provide. Let me know if I can help you to reproduce the error.
<details>

```
Traceback (most recent call last):
  File "/Users/fritzobermeyer/github/uber/pyro/examples/air/main.py", line 328, in <module>
    main(**vars(parser.parse_args()))
  File "/Users/fritzobermeyer/github/uber/pyro/examples/air/main.py", line 215, in main
    loss = svi.step(X, args.batch_size, z_pres_prior_p=partial(z_pres_prior_p, i))
  File "/Users/fritzobermeyer/github/uber/pyro/pyro/infer/svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/Users/fritzobermeyer/github/uber/pyro/pyro/infer/elbo.py", line 65, in loss_and_grads
    return self.which_elbo.loss_and_grads(model, guide, *args, **kwargs)
  File "/Users/fritzobermeyer/github/uber/pyro/pyro/infer/tracegraph_elbo.py", line 256, in loss_and_grads
    for weight, model_trace, guide_trace in self._get_traces(model, guide, *args, **kwargs):
  File "/Users/fritzobermeyer/github/uber/pyro/pyro/infer/tracegraph_elbo.py", line 211, in _get_traces
    check_model_guide_match(model_trace, guide_trace)
  File "/Users/fritzobermeyer/github/uber/pyro/pyro/util.py", line 363, in check_model_guide_match
    name, model_shape, guide_shape))
ValueError: Model and guide dims disagree at site 'z_what_2': torch.Size([50]) vs torch.Size([64, 50])
```
</details>

**Comment by null-a** [comment]
> Would you mind taking a look at the error in air?

@fritzo: Sure thing. Pointers as to how to reproduce would be helpful. I'm currently seeing the following error what I run `examples/air/main.py`:

```
    torch_dist = torch.distributions.Bernoulli(probs=ps, logits=logits)
TypeError: __init__() got an unexpected keyword argument 'logits'
```

That's with `torch (0.3.0.post4)`.

**Comment by neerajprad** [comment]
@null-a - Could you try testing with PyTorch master branch? The easiest way to build it would be to download the CPU wheels from `s3://pyro-ppl/ci`, and installing it via pip in a separate virtual environment. Or else you could simply follow the instructions on PyTorch's README.

```
# Install awscli first - https://docs.aws.amazon.com/cli/latest/userguide/installing.html
mkdir -p tmp
# python 2.7
aws s3 --no-sign-request sync s3://pyro-ppl/ci tmp --exclude "*" --include "*-cp27-p*"
# python 3.5  
aws s3 --no-sign-request sync s3://pyro-ppl/ci tmp --exclude "*" --include "*-cp35-*"  
pip install tmp/*
rm -r tmp
```

**Comment by null-a** [comment]
> Could you try testing with PyTorch master branch?

@neerajprad: Great, with that I'm seeing the error, thanks.

> but I have been unable to pinpoint where the tensor of incorrect size torch.Size((50,)) is created.

@fritzo: If I apply [this diff](https://gist.github.com/null-a/ec1d56343983354fbff50701032bd66f) then `examples/air/main.py` runs OK. I'm not familiar with the recent changes, so I'm not sure if this is correct thing to do, but does that help?

**Comment by fritzo** [comment]
Thanks @null-a, your fix looks like the right thing to do.

**Comment by null-a** [comment]
@fritzo: Great. I guess there will need to be similar changes made to the AIR example notebook. I could take a look at that sometime, but I won't get to it today.

**Comment by neerajprad** [comment]
@fritzo - Should we modify the notebooks as well, or get this merged as is?

**Comment by fritzo** [comment]
I'd merge this as is. Authors of notebooks without unit tests are responsible for maintaining those notebooks by hand.

**Comment by fritzo** [comment]
@neerajprad Ready to merge? I'm wrapping Alican's Multinomial on top of this PR.

**Comment by neerajprad** [comment]
> Ready to merge? I'm wrapping Alican's Multinomial on top of this PR.

@fritzo - Merged. Could you merge `dev` into your Multinomial PR?

**Comment by null-a** [comment]
> Authors of notebooks without unit tests are responsible for maintaining those notebooks by hand.

Can you give me a pointer as to how I add unit tests for the AIR notebook. At the time I wrote this, I got the impression that basic checks for notebooks (that e.g. make sure they run without error) were in the works? I won't be manually checking the AIR notebook against every release, so without something like this it will rot.

**Comment by fritzo** [comment]
@null-a Here's a possible way to test tutorials on CI: https://github.com/uber/pyro/pull/678

**Pull request merged**
