### PR TITLE
New version of IAF and inversion operator

### PR DESCRIPTION
**Pull request by stefanwebb**
The default version of IAF uses a slightly different equation with better properties. The old version of IAF is renamed `InverseAutoregressiveFlowStable`. Both now have an inversion operator that is called when the inverse is not in the cache.

### CODE REVIEW

**Comment by stefanwebb** [comment]
Is it possible to put display mode equations in the documentation?

**Comment by eb8680** [comment]
> Is it possible to put display mode equations in the documentation?

Yep, see e.g. the `pyro.contib.glmm` docs: https://github.com/uber/pyro/blob/dev/pyro/contrib/glmm/glmm.py#L130

**Comment by stefanwebb** [comment]
There might be a chance for a small amount of code reuse... Let me see what a `InverseAutoregressiveFlowBase` class for this would look like

**Comment by stefanwebb** [comment]
Cool, I'll put the basic equation that the flows use in the docs

**Comment by stefanwebb** [comment]
I've tried but I don't think it does simplify things, so I'd like to leave it as it is. The docs have the equations in them now

**Pull request merged**
