### PR TITLE
Fix profiling scripts after distributions refactor

### PR DESCRIPTION
**Pull request by neerajprad**
Due to distribution API changes, the profiling script was broken. This fixes the script to work with the changed API.

### CODE REVIEW

**Comment by fritzo** [comment]
Should we add the profiling script to any unit tests? I've usually done this in the past, where the script is parameterized by `num_samples` or some other cost parameter and tests run with small cost.

**Comment by neerajprad** [comment]
> Should we add the profiling script to any unit tests? I've usually done this in the past, where the script is parameterized by num_samples or some other cost parameter and tests run with small cost.

If it is with an aim to prevent breakages - we can just add `python -m profiler.distributions` to .travis.yml`, to quickly check if the script works as expected (shouldn't take any time). I will do that actually. If it is to actually test perf regression, that'll need some more thinking.

**Comment by fritzo** [comment]
Let's add `python -m profiler.distributions` to `.travis.yml` as you suggest, that sounds like a good idea.

**Comment by neerajprad** [comment]
> Let's add python -m profiler.distributions to .travis.yml as you suggest, that sounds like a good idea.

Done.

**Comment by fritzo** [comment]
Looks great. I'll merge as soon as tests pass.

**Pull request merged**
