### PR TITLE
Bump to version 0.1.1

### PR DESCRIPTION
**Pull request by fritzo**

### CODE REVIEW

**Comment by martinjankowiak** [comment]
@fritzo merge?

**Comment by fritzo** [comment]
yes, and I'll publish

**Comment by fritzo** [comment]
done, it's now on pip

**Comment by jpchen** [comment]
Can we do a merge to master with the tag?

**Comment by fritzo** [comment]
Done, thanks for the reminder. I'll try to keep master in sync with the latest release henceforth.

**Pull request merged**
