### PR TITLE
Upgrade to latest pytorch master

### PR DESCRIPTION
**Pull request by neerajprad**
PyTorch CI wheels are updated.

### CODE REVIEW

**Comment by neerajprad** [comment]
@fritzo - By upgrading to PyTorch master, the `torch.poisson` function only accepts `DoubleTensor` now.

```
>>> import torch
>>> torch.poisson(torch.tensor([1]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: expected scalar type Double but found Float

>>> torch.poisson(torch.DoubleTensor([1]))
 2
[torch.DoubleTensor of size (1,)]
```

Is that expected, or some regression? cc. @apaszke

**Comment by apaszke** [comment]
I don't think that is expected

**Comment by neerajprad** [comment]
> I don't think that is expected

Should I create an issue in PyTorch to investigate further?

**Comment by apaszke** [comment]
Yes, please!

**Comment by neerajprad** [comment]
@martinjankowiak, @jpchen - Can we merge this? This will fix the currently broken build due to the change in CI wheels (issue mentioned above).

**Pull request merged**
