### PR TITLE
Include AIR tutorial in smoke tests.

### PR DESCRIPTION
**Pull request by null-a**
This is an attempt to include the AIR tutorial in new (#678) tutorial smoke tests. I'm not making use of the `smoke_test` flag within the tutorial as none of its cells do much work. This works locally, but I'll keep an eye on travis in case of problems.

### CODE REVIEW

**Comment by null-a** [comment]
I've added the execution counts to the repo by running the notebook locally, and then running `nbstripout --keep-count`. Let's see if the tests pass with this.

**Comment by fritzo** [comment]
Well I'm not opposed to pinning to an old "working" version of `nbval==0.7` if that's the easiest solution :smile:

**Comment by fritzo** [comment]
Actually I recall being unable to load a tutorial notebook due to a `cell_count=None` error at some point, so `--keep-count` sounds like a good idea.

**Comment by fritzo** [comment]
@null-a Do you want me to merge this as-is, or do you want to add `--keep-count` to the `scrub` command in `Makefile`?

**Comment by null-a** [comment]
@fritzo I don't have a preference, happy to go with whatever seems best to you. If you'd like the `Makefile` updating, I can do it as part of this.

**Comment by fritzo** [comment]
We can do it in a late PR. merging. Thanks for adding this!

**Comment by null-a** [comment]
@fritzo: no worries, thanks for your help.

**Pull request merged**
