### PR TITLE
Split LambdaPoutine into ScalePoutine + IndepPoutine

### PR DESCRIPTION
**Pull request by fritzo**
This is a pure refactoring PR.

## Why?

This will make it easy to scale different parts of a dataset, e.g. in stratified sampling for fraud detection.

### CODE REVIEW

**Comment by fritzo** [comment]
@martinjankowiak Mind if I do the `map_data_stack` cleanup in a separate PR? I'd like to rename it to `cond_indep_stack` and reverse it (to be more pythonic).

**Comment by martinjankowiak** [comment]
@fritzo i suppose that's ok... seems awfully indulgent with our limited travis cores though ; )

**Comment by fritzo** [comment]
Ready to merge.

**Comment by fritzo** [comment]
Thanks, Martin!

**Pull request merged**
