### PR TITLE
bayesian regression tutorial part i

### PR DESCRIPTION
**Pull request by jpchen**
these intro two tutorials are a rehash of  #1282 and the existing tutorial.

This tutorial covers:
- linear regression
- bayesian linear regression via `random_module`
- autoguide (diagnormal)

part 2 shortly to follow

**TODO:**
- [x] posterior marginal plot 
- [x] explain autoguides
- [x] add proper links
- [x] add ref

### CODE REVIEW

**Comment by robsalomone** [comment]
Hi @jpchen , am happy to give feedback on this if you can give me a few days.

**Comment by jpchen** [comment]
@robsalomone we are releasing this week, so the earlier the better. also happy to address any comments you have in a follow up PR

**Comment by eb8680** [comment]
What do you think about having `random_module` and `autoguide` in part 2 instead of part 1?  It seems like we should introduce those as tools for eliminating boilerplate rather than the default idiom for regression, since they don't work that well for nonlinear regression.

**Comment by robsalomone** [comment]
> @robsalomone we are releasing this week, so the earlier the better. also happy to address any comments you have in a follow up PR

Hi @jpchen , sounds good, as this is already merged now I'll give feedback down the line and you can follow up.

**Pull request merged**
