### PR TITLE
[Do Not Merge] Bayesian Regression Tutorial

### PR DESCRIPTION
**Pull request by neerajprad**
Opening a PR to track and easily view the current draft of the bayesian regression example. This is mostly for @eb8680. Please feel free to edit directly, but give a heads up so as to avoid painful merge conflicts.

### CODE REVIEW

**Comment by martinjankowiak** [comment]
nice! 

so... why not just use sns.regplot? ; )

**Comment by neerajprad** [comment]
> so... why not just use sns.regplot? ; )

Haha..now that would be cheating!

**Comment by jpchen** [comment]
these plots look fantastic, idk what the long-term plans for this, but if it wont get merged into dev, itd be nice to bootstrap some of this for the existing bayesian regression tutorial. thats due for a rewriting sometime anyhow...

**Comment by neerajprad** [comment]
> these plots look fantastic, idk what the long-term plans for this, but if it wont get merged into dev, itd be nice to bootstrap some of this for the existing bayesian regression tutorial. thats due for a rewriting sometime anyhow...

This will probably also benefit from some more description if we decide to put it as an example. Maybe we can revisit this after UAI, and I agree that the existing bayesian regression example is a nice self-contained piece that shows the use of `random_module/lift` (feel free to pick out any pieces from here if you think that might help)!

**Comment by jpchen** [comment]
closing in favor of #1630

**Pull request closed without merging**
