### PR TITLE
Tutorial on deep gaussian process

### PR DESCRIPTION
**Pull request by fehiepsi**
This PR tracks the progress of making deep gaussian process tutorial. It will be great to be able to answer the following questions in this tutorial:

- how to stack many GPs layers and do inference
- how to do inference with HMC
- how to make a mean function

### CODE REVIEW

**Comment by martinjankowiak** [comment]
@fehiepsi i think we need to think carefully about which/how many tutorials we want. every tutorial we add has a cost in both: i) review and ii) maintenance. also, at the end of the day pyro is not a GP library, so it doesn't make sense to have excessively many GP tutorials. maybe we haven't reached that point yet, but it is something to keep in mind. also, if we move towards closer integration with gpytorch (which i am convinced we should) then tutorials will in any case require rewriting once the code integration is complete. broadly, i think we should think more carefully about where we want to take `pyro.contrib.gp` before adding much in the way of code/tutorials.

**Comment by fehiepsi** [comment]
Hi Martin, thanks for your feedback! I have thought about the issues which you proposed. I intend to make this last one to show the flexibility of Pyro GP. Pyro GP has most features which other GP libraries have (not including GPyTorch). The features in this tutorial (HMC training, stacking layers) are hidden in the tests, so it is good idea to let users know. Anyway, I am persuaded that it is better to write a blog for it instead of putting in Pyro tutorials. So I will close this and the issue #1549.

**Comment by RPrudden** [comment]
@fehiepsi did you ever end up writing this blog post?

**Comment by fehiepsi** [comment]
@RPrudden Sorry, I don't have time recently. I should keep my words to write a blog-post about it. I will do  this or the next weekend and let you know.

**Comment by fehiepsi** [comment]
@RPrudden You can find a simple tutorial [here in my blog](https://fehiepsi.github.io/blog/deep-gaussian-process/). It includes doing HMC/SVI for deep GPs. Hope that you will enjoy it. :)

**Pull request closed without merging**
