### PR TITLE
[WIP] Revert sudo=false in .travis.yml

### PR DESCRIPTION
**Pull request by fritzo**
https://github.com/travis-ci/travis-ci/issues/5623

### CODE REVIEW

**Comment by neerajprad** [comment]
Lets see how the test times look before merging.

**Comment by fritzo** [comment]
did you click on the link?

we're trying desparately to diagnose why our builds are taking so long.

**Comment by jpchen** [comment]
@fritzo that was changing it to true. "revert" suggests there was a PR to make it `False` in the first place

**Comment by neerajprad** [comment]
@jpchen - we changed this in #520where we previously had `sudo: required` (which is the same as `sudo: true`).

**Comment by fritzo** [comment]
@jpchen sorry, I misunderstood your question. When Travis-ci released containers a few years ago, they wanted people to try it out so they claimed "containers are faster, so add sudo=false in your build". We believed them. In practice there is negligible speedup and possibly a slowdown, as in the link.

**Comment by neerajprad** [comment]
Check this out - https://www.traviscistatus.com/. The backlog for open source (container projects) seems to have some spiky behavior which isn't there for non container based projects.

@fritzo - We still have this issue of `no response received within 10 mins` for one of the integration test runs. Also, comparing this with #548 (which removes xdist and sets sudo to true), there seems to be some benefit (small) to parallelizing on both the cores.

**Comment by fritzo** [comment]
Closing in favor of #548

**Pull request closed without merging**
