### PR TITLE
rework bo tutorial

### PR DESCRIPTION
**Pull request by martinjankowiak**
@fehiepsi i've made a first pass. i rearranged things a bit to make the text consistent with the code. let me know if you dislike any of the changes i've made or if you have suggestions for further improvements

### CODE REVIEW

**Comment by fehiepsi** [comment]
Ah, there might be some issues when rendering to html. But we can do it later. :)

**Comment by martinjankowiak** [comment]
@fehiepsi ok great. i increased the number of seed values to 5 and changed the random number seed. looks better now, i tink.

@jpchen can you please check if this renders reasonably in html?

if it renders ok should be ready to merge (unless there are other review comments out there)

**Comment by jpchen** [comment]
@martinjankowiak can you resolve merge conflicts first so i can check the final result

**Comment by martinjankowiak** [comment]
@jpchen thanks, done

**Pull request merged**
