### PR TITLE
fail docs build on warnings

### PR DESCRIPTION
**Pull request by jpchen**
travis will now catch docs errors that rtd [cannot](https://github.com/rtfd/readthedocs-build/issues/25) [catch](https://github.com/rtfd/readthedocs-build/issues/7) and prevent silent fails like #964

### CODE REVIEW

**Comment by fritzo** [comment]
Do you think it's worth adding a comment to `setup.py`?
```diff
    author_email='pyro@uber.com',
    install_requires=[
+       # If you add libraries here, please also add them to docs/requirements.txt
        'contextlib2',
        'graphviz>=0.8',
        'networkx>=2.0.0',
        'six>=1.10.0',
        'torch',
    ],
```

**Comment by jpchen** [comment]
> Do you think it's worth adding a comment...

done.

**Comment by neerajprad** [comment]
LGTM. 

@jpchen - Should I merge this?

**Comment by jpchen** [comment]
ya

**Pull request merged**
