### PR TITLE
Add an implementation of forward filtering / backward sampling

### PR DESCRIPTION
**Pull request by eb8680**
Addresses #915 
Blocked by #1359 
Pair coded with @fritzo 

This PR adds a new `Messenger` in `pyro/infer/traceenum_elbo.py` and a new method `TraceEnum_ELBO.sample_posterior` for sampling from the joint posterior distribution of all latent variables in a model given all observed variables.

## Tasks

- [x] support sampling continuous RVs from the posterior, rather than the guide. this is needed e.g. to sample from continuous RVs that depend only on an enumerated RV, as in continuous features of treecat. this should be as easy as removing the model-guide mismatch error from `get_importance_traces()`.

## Tested
- [x] Smoke test with simplified TreeCat
- [x] Death tests for invalid configurations
- [x] Tests for correctness

### CODE REVIEW

**Comment by fritzo** [comment]
@eb8680 would you like me to resolve merge conflicts?

**Comment by eb8680** [comment]
> would you like me to resolve merge conflicts?

Since #1359 is mostly done, we might as well just get that merged first

**Comment by fritzo** [comment]
@eb8680 do you mind if I resolve merge conflicts in this branch so I can start building an example on top of it?

**Comment by eb8680** [comment]
> do you mind if I resolve merge conflicts in this branch so I can start building an example on top of it?

Nope, go ahead

**Pull request merged**
