### PR TITLE
AIR tutorial: Show example data points as promised in the text.

### PR DESCRIPTION
**Pull request by null-a**
The main text is written with the expectation that the contents of this cell will show up, so this sets `keep_output=True` etc.

### CODE REVIEW

**Comment by null-a** [comment]
CI failure appears to be unrelated to this change, error message mentions `tests/infer/test_enum.py`?

**Comment by eb8680** [comment]
I restarted the builds.  Maybe related to #514?  Also, @jpchen what's up with the Travis tutorial failures?

**Comment by jpchen** [comment]
i believe thats because it is trying to run the cells but not all the tutorials are runnable
cc-ing @neerajprad since he would know

**Comment by neerajprad** [comment]
The travis-tutorial stage should not impact the build result. It would fail if any of the notebook cells errors when the tool tries to run it. Since our tutorials are not all runnable (except for bayesian regression), it is expected to fail. 

We should either annotate the non runnable cells by using the comment `#NBVAL_SKIP`, or remove this from travis if it is too much effort to support this in our tutorials. @fritzo - what do you think?

**Comment by neerajprad** [comment]
I am taking a look at #514. The test seems to pass locally, but is failing on travis non-deterministically.

**Comment by neerajprad** [comment]
@null-a, @eb8680 :  we do not need to wait on the test results to merge this, since this is only touching the tutorials.

**Comment by fritzo** [comment]
I think it's reasonable to remove the tutorial stage from Travis tests for now, especially since we're having such difficulties with travis-ci.org. If we remove that, we should at least file an issues to get tutorial tests working, since we've already seen a few bugs in tutorials due to lack of tests.

**Comment by neerajprad** [comment]
> If we remove that, we should at least file an issues to get tutorial tests working, since we've already seen a few bugs in tutorials due to lack of tests.

I am removing this in #520. If the changes seem to work, I will create an issue to reinstate the tutorial stage once our CI issues are resolved.

**Pull request merged**
