### PR TITLE
Move einsum sharing logic upstream

### PR DESCRIPTION
**Pull request by fritzo**
~~Blocked by https://github.com/dgasmith/opt_einsum/pull/43~~
This can be merged as soon as `shared_intermediates` is released.

I've retained the tests to ensure the move went smoothly.

### CODE REVIEW

**Comment by fritzo** [comment]
@neerajprad I've merged your #1346 into this PR

**Comment by neerajprad** [comment]
LGTM! I am not sure why `test_elbo_dbn_growth` is failing though, and I'm not able to reproduce it locally.

**Comment by fritzo** [comment]
I'll just disable the test. It is mostly for profiling anyway.

**Comment by neerajprad** [comment]
Can we merge this?

**Comment by fritzo** [comment]
Yes, ready to merge.

**Pull request merged**
