### PR TITLE
Bump to PyTorch 0.3 on Travis-CI

### PR DESCRIPTION
**Pull request by fritzo**

### CODE REVIEW

**Comment by neerajprad** [comment]
The wheel has size 593 MB? Something is wrong here.

```
$ if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl; else pip install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl; fi
Collecting torch==0.3.0.post4 from http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl
  Downloading http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl (592.8MB)
    77% |████████████████████████▊       | 457.3MB 49.6MB/s eta 0:00:03
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
  Downloading http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl (592.8MB)
    77% |████████████████████████▊       | 457.3MB 49.6MB/s eta 0:00:03
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
The job has been terminated
```

**Comment by neerajprad** [comment]
> The wheel has size 593 MB? Something is wrong here.

The previous one was 341 MB, so I suppose this is in the ballpark. Let me see why the log is getting full.

**Comment by fritzo** [comment]
I've requested a small CPU-only package https://github.com/pytorch/pytorch/issues/4178 @soumith also mentioned this possibility on slack.

**Comment by erikreppel** [comment]
Is there an update on when this might get merged in? Would be great to be able to use latest PyTorch.

**Comment by fritzo** [comment]
@erikreppel Pyro already works with PyTorch 0.3 and we regularly work with PyTorch master. This issue is about testing on travis-ci.org.

**Comment by erikreppel** [comment]
@fritzo ah okay, I tried to install pyro in a new env the other day and had a version mismatch with pytorch 0.3, I thought this was the PR but the issue seems to have been resolved, sorry about that.

**Pull request closed without merging**
