### PR TITLE
add forum to readme

### PR DESCRIPTION
**Pull request by jpchen**

### CODE REVIEW

**Comment by neerajprad** [comment]
We should add a link to the website too?

**Comment by jpchen** [comment]
the massive logo is a link to the website. do we need an explicit link?

**Comment by neerajprad** [comment]
> the massive logo is a link to the website. do we need an explicit link?

I meant a link to the discussion forums from the website. :) Not related to this PR though.

**Comment by jpchen** [comment]
isnt it there already?

**Comment by neerajprad** [comment]
My bad..its there in the upper right corner. Missed it, I was looking at the four links on the main page.

**Pull request merged**
