### PR TITLE
some tutorial improvements

### PR DESCRIPTION
**Pull request by randommm**
Fixes:

* At least for me, assignment on `data[0:6, 0].data` doesn't seem to work, the `Variable` is not changed. 
* Missing a `"\n",` was preventing a bullet list to be rendered correctly on `tutorial/source/svi_part_i.ipynb`.

### CODE REVIEW

**Comment by martinjankowiak** [comment]
@randommm what version of pytorch are you using?
```python
data[0:6, 0].data = torch.ones(6) 
```
should work fine

**Comment by randommm** [comment]
Hi, I think it's `0.3.0.post4`, here's the full output:

```
Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from __future__ import print_function
   ...: import numpy as np
   ...: import torch
   ...: from torch.autograd import Variable
   ...: import pyro
   ...: from pyro.optim import Adam
   ...: from pyro.infer import SVI
   ...: import pyro.distributions as dist
   ...: 
   ...: # clear the param store in case we're in a REPL
   ...: pyro.clear_param_store()
   ...: 
   ...: # create some data with 6 observed heads and 4 observed tails
   ...: data = Variable(torch.zeros(10, 1))
   ...: 

In [2]: data[0:6, 0].data = torch.ones(6)

In [3]: data
Out[3]: 
Variable containing:
    0
    0
    0
    0
    0
    0
    0
    0
    0
    0
[torch.FloatTensor of size 10x1]

In [4]: torch.__version__
Out[4]: '0.3.0.post4'
```

**Comment by randommm** [comment]
interestingly, `data.data[0:6, 0] = torch.ones(6)` seems to work.

**Comment by martinjankowiak** [comment]
ok can you please change it to 

data.data[0:6, 0] = torch.ones(6)

and i'll merge. thanks!

**Comment by randommm** [comment]
OK, done it!

**Pull request merged**
