### PR TITLE
Add Codecov to Travis

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Example report https://codecov.io/gh/gliptak/pyro/branch/codecov1

### CODE REVIEW

**Comment by neerajprad** [comment]
Thanks for adding a code coverage report to Pyro. Just to confirm - it looks like this is using all the test stages from travis? Would it be simple to remove one or more stages from the coverage report, say the examples stage for instance?

**Comment by neerajprad** [comment]
> Would it be simple to remove one or more stages from the coverage report, say the examples stage for instance?

I think we can just remove the `--cov` invocation from pytest for those stages. We can do that later (it won't really affect the marginal code coverage so we could leave it in as well) and add a badge to our README too. 

LGTM. @jpchen, @fritzo - Let me know if you have any thoughts / comments on inc. a code coverage report for PRs.

**Comment by jpchen** [comment]
> I think we can just remove the --cov invocation from pytest for those stages

sounds fine to me. i dont really know how accurate this is, afaik it does static analysis of coverage and cant do anything fancy like testing going down different branches in models with dynamic control flow

**Comment by gliptak** [comment]
@jpchen Thank you for the pointer
@neerajprad The easiest way to exclude would be to not generate coverage for example
https://github.com/uber/pyro/blob/dev/.travis.yml#L75
I will update the PR

**Comment by neerajprad** [comment]
> @neerajprad The easiest way to exclude would be to not generate coverage for example
https://github.com/uber/pyro/blob/dev/.travis.yml#L75

That's right. we can just remove it from the examples stage.

**Comment by gliptak** [comment]
Updated as per above, please review

**Comment by neerajprad** [comment]
Looks good! Thanks for contributing.

**Pull request merged**
