### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by fritzo**
Addresses #228 

## Why?

https://www.contributor-covenant.org/

## How?

This is a standard coc recommended by Github. I've used my email address but am open to alternatives.

Tests cancelled.

### CODE REVIEW

**Comment by ngoodman** [comment]
i'm really glad you started this!

is it permissible to edit the doc? if so, i'd like to do some small changes to emphasize that we expect positive and kind interactions (not just no harrasment).

can we make pyro@uber a publicly sendable list and use that address, so the whole burden isn't on @fritzo?

**Comment by fritzo** [comment]
@ngoodman Sure I'd love it if pyro@uber.com were public.

> is it permissible to edit the doc?

Absolutely, even encouraged. Feel free to push directly to this branch. However I'd recommend creating a follow-up PR to keep track of the positive changes you make. That way we could have "be nice" commit in our git history 😄

**Comment by fritzo** [comment]
Can we merge this and punt edits to a follow-up PR?

**Comment by fritzo** [comment]
@neerajprad would you mind merging this?

**Comment by neerajprad** [comment]
> @neerajprad would you mind merging this?

Done. 

@ngoodman - Please feel free to make edits to this in a subsequent PR!

**Pull request merged**
